"""Quant report generator."""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional

from sas.quant.agents import (
    AgentCapabilities,
    QuantAgent,
    backtest_agent,
    data_researcher,
    execution_agent,
    portfolio_agent,
    quant_coordinator,
    risk_agent,
    signal_researcher,
)
from sas.quant.backtest import BacktestConfig, BacktestEngine, BacktestResult
from sas.quant.broker import Account, BrokerConfig, Fill, Order, SimulatedBroker
from sas.quant.broker.adapter import BrokerAdapter
from sas.quant.broker.alpaca import AlpacaBrokerAdapter
from sas.quant.cli import register
from sas.quant.engine import EngineConfig, QuantEngine
from sas.quant.evaluation import (
    BenchmarkResult,
    BenchmarkRunner,
    RunEvaluator,
    aggregate_benchmark,
    artifact_has_field,
    computation_has_hash,
    compute_pass_k,
    evaluate_sovereignty,
    has_artifact_type,
    report_contains_findings,
    report_has_provenance,
    result_in_range,
)
from sas.quant.experiment import (
    AblationBatch,
    AblationConfiguration,
    AblationMatrix,
    AblationResult,
    CalibrationBatch,
    CalibrationMatrix,
    CalibrationResult,
    ComparativeAnalysis,
    ComparativeFinding,
    ComparisonResult,
    DataGeneratingProcess,
    ExperimentMatrix,
    ExperimentMetrics,
    ExperimentResult,
    ExperimentRunner,
    ExperimentSpec,
    GateAnalysisResult,
    GateOperatingCharacteristic,
    GateRecord,
    IncumbentTurnover,
    NominalVsDefensible,
    ReflectionImpact,
    SignalCalibrationBatch,
    SignalCalibrationMatrix,
    SignalCalibrationResult,
    StrategyDiversity,
    SyntheticWorld,
    TrialEfficiency,
    ValidationCheck,
    ValidationReport,
    analyze_gate_operating_characteristics,
    analyze_matrix,
    compare_trial_budgets,
    compare_universes,
    compute_experiment_metrics,
    evaluate_with_configuration,
    generate_ablation_report,
    generate_calibration_report,
    generate_experiment_matrix,
    generate_gate_analysis_report,
    generate_null_world,
    generate_report,
    generate_signal_calibration_report,
    generate_signal_world,
    run_confounder_matrix,
    get_standard_configurations,
    run_ablation_matrix,
    run_comparison,
    run_experimental_suite,
    run_governed_experiment,
    run_null_calibration,
    run_signal_calibration,
    run_ungoverned_experiment,
    validate_experiment,
    validate_matrix,
)
from sas.quant.knowledge.compiler import QuantKnowledgeCompiler
from sas.quant.lifecycle import TRANSITIONS, ResearchLifecycle, ResearchStage
from sas.quant.market import (
    DatasetInfo,
    LocalCSVDataset,
    MarketDataPoint,
    MarketDataProvider,
    SyntheticDataProvider,
)
from sas.quant.model import (
    ModelAdapter,
    ModelResponse,
    OllamaModelAdapter,
    OpenAIModelAdapter,
    StubModelAdapter,
    ToolCallRequest,
    ToolCallResult,
    ToolFormatter,
    create_model_adapter,
)
from sas.quant.orchestration import (
    OrchestratorConfig,
    OrchestratorResult,
    QuantResearchOrchestrator,
)
from sas.quant.orchestration.gate import (
    AuthorizationResult,
    SessionLimits,
    TradeAuthorization,
)
from sas.quant.provenance import ProvenanceGraph, ProvenanceNode
from sas.quant.reports import QuantReport, ReportGenerator
from sas.quant.risk import RiskEngine, RiskEvaluation, RiskPolicy, TradeIntent
from sas.quant.strategy import (
    PositionSizing,
    RiskConstraints,
    SignalDefinition,
    StrategyArtifact,
    TransactionCosts,
)
from sas.quant.toolbox import QuantToolbox, ToolDefinition, create_toolbox_from_world
from sas.quant.world import (
    CapabilityComposition,
    Criterion,
    CriterionResult,
    Evidence,
    ExecutionRun,
    ModelAdapter,
    QuantWorld,
    QuantWorldBuilder,
    Rubric,
    RunEvaluation,
    Task,
    TrajectoryStep,
)
from sas.quant.worlds.adversarial import ADVERSTIONAL_WORLDS
from sas.quant.worlds.portfolio_intelligence import (
    PORTFOLIO_INTELLIGENCE_GOLD,
    PORTFOLIO_INTELLIGENCE_RUBRIC,
    PORTFOLIO_INTELLIGENCE_TASK,
    PORTFOLIO_INTELLIGENCE_WORLD,
)

__version__ = "0.1.0a0"
__all__ = [
    "ADVERSTIONAL_WORLDS",
    "PORTFOLIO_INTELLIGENCE_GOLD",
    "PORTFOLIO_INTELLIGENCE_RUBRIC",
    "PORTFOLIO_INTELLIGENCE_TASK",
    "PORTFOLIO_INTELLIGENCE_WORLD",
    "TRANSITIONS",
    "Account",
    "AgentCapabilities",
    "AuthorizationResult",
    "BacktestConfig",
    "BacktestEngine",
    "BacktestResult",
    "BenchmarkResult",
    "BenchmarkRunner",
    "AlpacaBrokerAdapter",
    "BrokerAdapter",
    "BrokerConfig",
    "CapabilityComposition",
    "Criterion",
    "CriterionResult",
    "DataGeneratingProcess",
    "DatasetInfo",
    "EngineConfig",
    "Evidence",
    "ExecutionRun",
    "ExperimentMatrix",
    "ExperimentMetrics",
    "ExperimentResult",
    "ExperimentRunner",
    "ExperimentSpec",
    "Fill",
    "IncumbentTurnover",
    "LocalCSVDataset",
    "MarketDataPoint",
    "MarketDataProvider",
    "ModelAdapter",
    "ModelResponse",
    "NominalVsDefensible",
    "OllamaModelAdapter",
    "OpenAIModelAdapter",
    "Order",
    "OrchestratorConfig",
    "OrchestratorResult",
    "PositionSizing",
    "ProvenanceGraph",
    "ProvenanceNode",
    "QuantAgent",
    "QuantEngine",
    "QuantKnowledgeCompiler",
    "QuantReport",
    "QuantResearchOrchestrator",
    "QuantToolbox",
    "QuantWorld",
    "QuantWorldBuilder",
    "ReflectionImpact",
    "ReportGenerator",
    "ResearchLifecycle",
    "ResearchStage",
    "RiskConstraints",
    "RiskEngine",
    "RiskEvaluation",
    "RiskPolicy",
    "Rubric",
    "RunEvaluation",
    "RunEvaluator",
    "SessionLimits",
    "SignalDefinition",
    "SimulatedBroker",
    "StrategyArtifact",
    "StrategyDiversity",
    "StubModelAdapter",
    "SyntheticDataProvider",
    "SyntheticWorld",
    "Task",
    "ToolCallRequest",
    "ToolCallResult",
    "ToolDefinition",
    "ToolFormatter",
    "TradeAuthorization",
    "TradeIntent",
    "TrajectoryStep",
    "TransactionCosts",
    "TrialEfficiency",
    "ValidationCheck",
    "ValidationReport",
    "aggregate_benchmark",
    "analyze_matrix",
    "artifact_has_field",
    "backtest_agent",
    "compare_trial_budgets",
    "compare_universes",
    "computation_has_hash",
    "compute_experiment_metrics",
    "compute_pass_k",
    "create_model_adapter",
    "create_toolbox_from_world",
    "data_researcher",
    "evaluate_sovereignty",
    "execution_agent",
    "generate_experiment_matrix",
    "generate_null_world",
    "generate_report",
    "generate_signal_world",
    "run_confounder_matrix",
    "has_artifact_type",
    "portfolio_agent",
    "quant_coordinator",
    "register",
    "report_contains_findings",
    "report_has_provenance",
    "result_in_range",
    "risk_agent",
    "run_experimental_suite",
    "signal_researcher",
    "validate_experiment",
    "validate_matrix",
]
